on:
  push

name: Scan repo workflow

jobs:
  my-job:
    name: ci scan job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: scan
      uses: ./
      env:
        CS_API_TOKEN: ${{ secrets.CS_API_TOKEN }}
        CS_SCAN_URL: http://a523f93b688e646f9885a8aae51ef68e-1520368521.ap-southeast-1.elb.amazonaws.com:7778
